name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.11
      - name: Init
        run: terraform init terraform
      - name: Plan
        run: terraform plan terraform
