name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.11
      - name: TFNotify install
        run: >
          sudo curl -fL -o tfnotify.tar.gz https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz ;
          sudo tar -C /usr/bin -xzf ./tfnotify.tar.gz ;

      - name: Init
        run: terraform init terraform
      - name: Plan
        run: >
          terraform plan -no-color terraform |\
          /usr/bin/tfnotify --config ./tfnotify/github.yml plan --title "## Test"
