name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.11
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.12'
      - name: TFNotify install
        run: >
          go install github.com/mercari/tfnotify@v0.7.0 ;
      - name: init and plan
        run: >
          terraform init terraform ;
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" ;
          terraform plan -no-color terraform | ~/go/bin/tfnotify --config ./tfnotify/github.yml plan --title "## Test" ;
